import React, { useState } from 'react';
import { X, Share2, Copy, Download, MapPin, Calendar, Clock } from 'lucide-react';
import { formatDate, formatDuration } from '../utils/helpers';

export default function ShareableSummary({ recording, onClose }) {
  const [copied, setCopied] = useState(false);

  const summaryData = {
    interactionId: recording.id,
    date: formatDate(recording.startTime),
    startTime: new Date(recording.startTime).toLocaleTimeString(),
    endTime: new Date(recording.endTime).toLocaleTimeString(),
    duration: formatDuration(Math.floor(recording.duration / 1000)),
    location: recording.location ? 
      `${recording.location.latitude.toFixed(6)}, ${recording.location.longitude.toFixed(6)}` : 
      'Location not available',
    rightsExercised: [
      'Right to remain silent',
      'Right to refuse searches',
      'Right to record interaction'
    ],
    notes: 'Interaction documented using Pocket Protector app.'
  };

  const generateSummaryText = () => {
    return `INTERACTION SUMMARY
Generated by Pocket Protector

Interaction ID: ${summaryData.interactionId}
Date: ${summaryData.date}
Start Time: ${summaryData.startTime}
End Time: ${summaryData.endTime}
Duration: ${summaryData.duration}
Location: ${summaryData.location}

Rights Exercised:
${summaryData.rightsExercised.map(right => `• ${right}`).join('\n')}

Notes: ${summaryData.notes}

Generated on: ${new Date().toLocaleString()}
`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generateSummaryText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy:', error);
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Interaction Summary',
          text: generateSummaryText(),
        });
      } catch (error) {
        console.error('Share failed:', error);
      }
    } else {
      handleCopy();
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50">
      <div className="bg-surface rounded-lg w-full max-w-md max-h-[90vh] overflow-hidden">
        <div className="flex items-center justify-between p-4 border-b">
          <h3 className="text-lg font-semibold">Interaction Summary</h3>
          <button
            onClick={onClose}
            className="p-1 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="overflow-y-auto max-h-96 p-4 space-y-4">
          {/* Basic Info */}
          <div className="bg-gray-50 rounded-lg p-3">
            <h4 className="font-semibold text-gray-800 mb-2">Interaction Details</h4>
            <div className="space-y-2 text-sm">
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 text-gray-500" />
                <span className="font-medium">Date:</span>
                <span>{summaryData.date}</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-gray-500" />
                <span className="font-medium">Duration:</span>
                <span>{summaryData.duration}</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPin className="w-4 h-4 text-gray-500" />
                <span className="font-medium">Location:</span>
                <span className="text-xs">{summaryData.location}</span>
              </div>
            </div>
          </div>

          {/* Rights Exercised */}
          <div className="bg-accent/5 rounded-lg p-3">
            <h4 className="font-semibold text-gray-800 mb-2">Rights Exercised</h4>
            <div className="space-y-1">
              {summaryData.rightsExercised.map((right, index) => (
                <div key={index} className="flex items-start gap-2 text-sm">
                  <div className="w-1.5 h-1.5 bg-accent rounded-full mt-2 flex-shrink-0" />
                  <span>{right}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Notes */}
          <div className="bg-blue-50 rounded-lg p-3">
            <h4 className="font-semibold text-gray-800 mb-2">Notes</h4>
            <p className="text-sm text-gray-700">{summaryData.notes}</p>
          </div>

          {/* Timestamp */}
          <div className="text-xs text-gray-500 text-center">
            Generated on {new Date().toLocaleString()}
          </div>
        </div>

        {/* Actions */}
        <div className="p-4 border-t bg-gray-50 space-y-2">
          <div className="flex gap-2">
            <button
              onClick={handleShare}
              className="flex-1 flex items-center justify-center gap-2 bg-accent text-white py-2 px-4 rounded-lg hover:bg-accent/90 transition-colors"
            >
              <Share2 className="w-4 h-4" />
              <span className="font-medium">Share</span>
            </button>
            <button
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center gap-2 bg-gray-600 text-white py-2 px-4 rounded-lg hover:bg-gray-700 transition-colors"
            >
              <Copy className="w-4 h-4" />
              <span className="font-medium">{copied ? 'Copied!' : 'Copy'}</span>
            </button>
          </div>
          
          <p className="text-xs text-gray-600 text-center">
            This summary can be shared with legal counsel or advocacy organizations.
          </p>
        </div>
      </div>
    </div>
  );
}